CREATE TABLE "recipient" (
  "recipient_name" text,
  "uei" text,
  "recipient_level" text
);

INSERT INTO "recipient" ("recipient_name","uei","recipient_level")
VALUES
('BOOZ ALLEN HAMILTON INC.','DS4MZBE4SFZ5','C'),
('BOOZ ALLEN & HAMILTON INC','JJSBTMSJAM63','C'),
('BOOZ ALLEN HAMILTON INC','JCBMLGPE6Z71','P'),
('BOOZ ALLEN HAMILTON INC.','U174VB2YA8K5','C'),
('BOOZ ALLEN HAMILTON INC.','VWE7ANVJJ948','C'),
('BOOZ ALLEN HAMILTON INC.','FMMGJ8CQA4F7','C'),
('BOOZ ALLEN HAMILTON INC.','CL7NAZKLSWJ4','C'),
('BOOZ ALLEN HAMILTON INC','JTR2WGJLDNQ1','C'),
('BOOZ ALLEN HAMILTON INC.','CZ26THPKFPJ9','C'),
('BOOZ ALLEN HAMILTON INC.','QG32JD7VVWK5','C');
